// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0yeD4Q1PXQaLZ8dRO2ttRCKhKEnIIS4',
    appId: '1:521714109954:web:34cd2b6eafffaa1844a11b',
    messagingSenderId: '521714109954',
    projectId: 'mekaapp-c92a1',
    authDomain: 'mekaapp-c92a1.firebaseapp.com',
    storageBucket: 'mekaapp-c92a1.appspot.com',
    measurementId: 'G-4WYZXNFTD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznw-ryyto9dPhN9eKyW_Of7CfHypmNXk',
    appId: '1:521714109954:android:525878b723cf581b44a11b',
    messagingSenderId: '521714109954',
    projectId: 'mekaapp-c92a1',
    storageBucket: 'mekaapp-c92a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriL40KqNx0aFAFozjnQzwwj7Z-fBuZJ4',
    appId: '1:521714109954:ios:bd1cf3b40f63daae44a11b',
    messagingSenderId: '521714109954',
    projectId: 'mekaapp-c92a1',
    storageBucket: 'mekaapp-c92a1.appspot.com',
    iosBundleId: 'com.meka.meka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBriL40KqNx0aFAFozjnQzwwj7Z-fBuZJ4',
    appId: '1:521714109954:ios:bd1cf3b40f63daae44a11b',
    messagingSenderId: '521714109954',
    projectId: 'mekaapp-c92a1',
    storageBucket: 'mekaapp-c92a1.appspot.com',
    iosBundleId: 'com.meka.meka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj0yeD4Q1PXQaLZ8dRO2ttRCKhKEnIIS4',
    appId: '1:521714109954:web:fb234de6b77469e544a11b',
    messagingSenderId: '521714109954',
    projectId: 'mekaapp-c92a1',
    authDomain: 'mekaapp-c92a1.firebaseapp.com',
    storageBucket: 'mekaapp-c92a1.appspot.com',
    measurementId: 'G-JEZQ7GYLX9',
  );
}
